# Site settings
title: Work Stuff
name : Morgan Bauer
email: mhbauer@us.ibm.com 
github: MHBauer

description: > # this means to ignore newlines until "baseurl:"
  work blog
baseurl: ""
url: "http://mhbauer.github.io" 
twitter_username: ibmhb
github_username: MHBauer
linkedin_username : morganbauer



permalink: /:year/:month/:day/:title/
paginate: 10


# Build settings
markdown: kramdown


gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

theme: jekyll-theme-midnight